name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
    
    - name: install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: build
      run: go build . 
      
    - name: vet & lint
      run: |
        go vet .
        golint .
    
    - name: test
      run: go test ./... -vv
